### ISSUE TITLE
TypeScript development environment setup

### ISSUE THREAD

**Issue by civilizeddev** [ncthbrt/nact#61]
@ncthbrt 

I checked out the branch `refactor-typescript`, on which you did some refactoring.

I found you changed many things in `nact-core`, but the others that depend on `nact-core` haven't been changed properly according to it.

Now it is failing to compile.

I wonder whether you used tsc compiler on your works.

If needed, I want to share with you something about TypeScript development environment and how to run tsc compiler.

And what kind of IDE do you use on development?

I'm using VSCode with some TS extensions, such as TSLint, TS Prettier.

It's good to use some kind of linter and code prettier (formatter).

Thank you.

**Comment by ncthbrt** [comment]
Hey. Sorry the branch is still in progress, as I was using it to experiment
to understand how Typescript might be used to type RouteThink. This
experimentation led to me being quite aggressive in refactoring the
codebase, so aware that it may have been breaking other parts of the code
base. I may have also made some mistakes due to a beginner's understanding
of how Typescript's structural typing works; for instance, so of the type
constraints may be incorrect/poorly expressed.

I'm also using VSCode for development.

**Comment by ncthbrt** [comment]
@civilizeddev I added typescript bindings to a beta release of nact. Hopefully they should fulfill your needs. Would love to get some feedback on them.
