### ISSUE TITLE
Typescript: Unable to call three arguments in dispatch function

### ISSUE THREAD

**Issue by zrrtcs** [ncthbrt/nact#77]
@ncthbrt 
Managed to install nact and used it in a typescript project.
However, i did not manage to run the ping pong example. 

## Expected Behavior

1. I should able to call the `dispatch` function in `nact/lib/functions.js` with three arguments.
2. The `ctx` from the callback function in `spawnStateless` should able to have sender property.

## Current Behavior

```
import nact from "nact";
const system = nact.start();
const delay = (time) => new Promise((res) => setTimeout(res, time));

const ping = nact.spawnStateless(system, async (msg, ctx) =>  {
  console.log(msg);
  await delay(500);
  
  // ERROR:
  // 1. Error message regarding ctx.sender
  // Property 'sender' does not exist on type 'ActorContext<any, ActorSystemRef>'.
  // 2. Error message regarding nact.dispatch
  // (property) self: nact.Ref<any>
  // Expected 2 arguments, but got 3.ts(2554)
  nact.dispatch(ctx.sender, ctx.name, ctx.self);
}, 'ping');
```

## Steps to Reproduce

1. Install nact version ~7.2.2
2. Run `examples/ping-pong/ping-pong-stateless.js` in typescript fashion

## Context
1. I am trying to use nact in a typescript project.
2. I have found also that in `refactor-typescript` branch: `https://github.com/ncthbrt/nact/blob/refactor-typescript/nact-core/src/functions.ts`, the dispatch function accepts only two arguments.

## Your Environment

* Version used: nact version 7.2.2
* Typescript version: 3.7.5

Are there any steps that I should be aware when using typescript in nact?
Thanks for the help.

**Comment by ncthbrt** [comment]
Hi @zrrtcs, I should probably make some notes in the docs about the differences between the typescript and JavasScript versions. The omission of the sender is by design in typescript. I came to the conclusion after multiple iterations and attempts in both typescript and ReasonML, that the addition of `ctx.sender` is incompatible with typed actors. 

The recommended alternative is to add a reference to the sender in the message protocol itself. For queries, where getting a reference beforehand is not possible, the `query` function takes in a message creator callback which allows one to inject the temporary reference into the message.
