### ISSUE TITLE
ActorContext type doesn't have ctx.sender property

### ISSUE THREAD

**Issue by 5HARK** [ncthbrt/nact#85]
```ActorContext``` type doesn't have ```ctx.sender``` property.
https://github.com/ncthbrt/nact/blob/b28048869c745b305c253d1b22c18c39ba26f122/lib/index.d.ts#L63-L70

but in official docs, when perform response of ```query```, ```ctx.sender``` is needed.
https://nact.io/en_uk/lesson/javascript/querying

so I did like this(workaround)
```typescript
// request
await query(actorX, (_: ActorX) => "Let there be light", 5000)

// response(In actorX's msg handler)
dispatch((ctx as any).sender, "and there was light")
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 7.1.3
* Environment name and version (e.g. Node v8.8): Node v10.18.1
* Server type and version: Ubuntu 20.04
* Operating System and version: Ubuntu 20.04
* Link to your project:

**Comment by ncthbrt** [comment]
Hi @5HARK I really need to update the docs on this.
Sender has been omitted from the typescript types by design as it is not really possible to correctly type sender. (I've tried, with no luck) 

The use of sender okayish in a dynamically typed actor system, but I actually think in general it's an antipattern.

The recommended approach is to include the sender in the message itself as this allows you to enforce the typing of the sender using typescript types. 

This would change your example to the following:

```typescript
// request
await query(actorX, (sender:  Ref<string>) => ({ sender, text: "Let there be light" }), 5000)

// response(In actorX's msg handler)
dispatch(msg.sender, "and there was light")
```

**Comment by 5HARK** [comment]
Thank you for your response. It helps me a lot :-)
